#!/bin/sh
fgWebappdir=${1}'/../workspace'
fgWebappname=default
fgXmx=256
fgXms=256
fgJavaRoot=${1}'/Contents/Resources/Java'
fgCache='var/cache/jetty'
fgJavalib='usr/lib'
fgStartcfg='etc/jetty/start.config'
fgJettyhome='usr/share/jetty'
fgConfhome='etc/jetty'
cd ${fgJavaRoot}
java -Djava.awt.headless=true '-Dfusegrid.webappdir='${fgWebappdir} '-Dfusegrid.webappname='${fgWebappname} '-Djava.io.tmpdir='${fgCache} '-Djava.library.path='${fgJavalib} '-DSTART='${fgStartcfg} '-Djetty.home='${fgJettyhome} '-Dconfig.home='${fgConfhome} '-Djava.class.path='${fgJettyhome}'/lib/start.jar' '-Xms'${fgXms}'m' '-Xmx'${fgXmx}'m' -jar ${fgJettyhome}'/lib/start.jar'
